cc_library(
    name = 'ftrl',
    extra_cppflags = [
        '-Wl,--no-as-needed',
        '-pthread',
        '-std=c++11',],
    srcs = [
    'ftrl.cc',],
    deps = [
        '//mmbiz/mmbizdatacomm/ftrl/ftrl_lr_64/common:common',
        '//mmbiz/mmbizdatacomm/ftrl/ftrl_lr_64/io:io',
    ],
)
