cc_library(
    name = 'ftrl',
    extra_cppflags = [
        '-Wl,--no-as-needed',
        '-pthread',
        '-std=c++11',],
    srcs = [
    'ftrl.cc',],
    deps = [
        '//mmbiz/mmbizdatacomm/ftrl/mmbizlr/src/common:common',
        '//mmbiz/mmbizdatacomm/ftrl/mmbizlr/src/io:io',
    ],
)
